// <auto-generated />
using System;
using Involys.Poc.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Involys.Poc.Api.Infrastructure.Data.Migrations.Postgres
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Infrastructure.Data.Models.Alerts.ClassificationDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_source_classification");
                });

            modelBuilder.Entity("Involys.QueryBuilder.Api.Infrastructure.Data.Models.QueryBuilder.FunctionDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_source_function");
                });

            modelBuilder.Entity("Involys.QueryBuilder.Api.Infrastructure.Data.Models.QueryBuilder.OrderByDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderDirection")
                        .HasColumnType("integer");

                    b.Property<int?>("TableFieldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("TableFieldId");

                    b.ToTable("data_source_orderBy");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ArithmeticOperatorDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_source_arithm_operators");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ClassificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<bool>("Distinct")
                        .HasColumnType("boolean");

                    b.Property<int?>("HavingConditionId")
                        .HasColumnType("integer");

                    b.Property<string>("SqlText")
                        .HasColumnType("text");

                    b.Property<int?>("WhereConditionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("HavingConditionId");

                    b.HasIndex("WhereConditionId");

                    b.ToTable("data_source_dataSources");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceFieldDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<bool>("CalculatedField")
                        .HasColumnType("boolean");

                    b.Property<int?>("DataSourceDataModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<int?>("FunctionId")
                        .HasColumnType("integer");

                    b.Property<bool>("GroupBy")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TableFieldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceDataModelId");

                    b.HasIndex("FunctionId");

                    b.HasIndex("TableFieldId");

                    b.ToTable("data_source_dataSource_fields");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceTableDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("integer");

                    b.Property<int?>("JoinId")
                        .HasColumnType("integer");

                    b.Property<bool>("MainEntity")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("JoinId");

                    b.HasIndex("TableId");

                    b.ToTable("data_source_dataSource_tables");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ClculatedField")
                        .HasColumnType("integer");

                    b.Property<int?>("DataSourceTableId")
                        .HasColumnType("integer");

                    b.Property<string>("ExpressionType")
                        .HasColumnType("text");

                    b.Property<int?>("FieldsDataSourceId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstTermId")
                        .HasColumnType("integer");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondTermId")
                        .HasColumnType("integer");

                    b.Property<int?>("TableFieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClculatedField");

                    b.HasIndex("DataSourceTableId");

                    b.HasIndex("FieldsDataSourceId");

                    b.HasIndex("FirstTermId")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.HasIndex("SecondTermId")
                        .IsUnique();

                    b.HasIndex("TableFieldId");

                    b.ToTable("data_source_expression_terms");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.JoinConditionDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ArithmeticOperatorId")
                        .HasColumnType("integer");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TableFieldDataModelFieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArithmeticOperatorId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TableFieldDataModelFieldId");

                    b.ToTable("data_source_join_conditions");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.JoinDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_source_joins");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.OperatorDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_source_operators");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_source_tables");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableFieldDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<bool>("IsList")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ReferenceFieldId")
                        .HasColumnType("integer");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceFieldId");

                    b.HasIndex("TableId");

                    b.ToTable("data_source_table_fields");
                });

            modelBuilder.Entity("Involys.QueryBuilder.Api.Infrastructure.Data.Models.QueryBuilder.OrderByDataModel", b =>
                {
                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceDataModel", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableFieldDataModel", "TableField")
                        .WithMany()
                        .HasForeignKey("TableFieldId");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceDataModel", b =>
                {
                    b.HasOne("Infrastructure.Data.Models.Alerts.ClassificationDataModel", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationId");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", "HavingCondition")
                        .WithMany()
                        .HasForeignKey("HavingConditionId");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", "WhereCondition")
                        .WithMany()
                        .HasForeignKey("WhereConditionId");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceFieldDataModel", b =>
                {
                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceDataModel", null)
                        .WithMany("DataSourceFields")
                        .HasForeignKey("DataSourceDataModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Involys.QueryBuilder.Api.Infrastructure.Data.Models.QueryBuilder.FunctionDataModel", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableFieldDataModel", "TableField")
                        .WithMany()
                        .HasForeignKey("TableFieldId");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceTableDataModel", b =>
                {
                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceDataModel", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.JoinDataModel", "Join")
                        .WithMany()
                        .HasForeignKey("JoinId");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableDataModel", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", b =>
                {
                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceFieldDataModel", "CalculatedFieldResulting")
                        .WithMany()
                        .HasForeignKey("ClculatedField")
                        .HasConstraintName("FK_calculated_FIELD");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceTableDataModel", "DataSourceTable")
                        .WithMany()
                        .HasForeignKey("DataSourceTableId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.DataSourceFieldDataModel", "FieldsDataSource")
                        .WithMany()
                        .HasForeignKey("FieldsDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", "FirstTerm")
                        .WithOne()
                        .HasForeignKey("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", "FirstTermId")
                        .HasConstraintName("FK_firstTerm")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.OperatorDataModel", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", "SecondTerm")
                        .WithOne()
                        .HasForeignKey("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ExpressionTermDataModel", "SecondTermId")
                        .HasConstraintName("FK_secondTerm")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableFieldDataModel", "TableField")
                        .WithMany()
                        .HasForeignKey("TableFieldId");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.JoinConditionDataModel", b =>
                {
                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.ArithmeticOperatorDataModel", "ArithmeticOperator")
                        .WithMany()
                        .HasForeignKey("ArithmeticOperatorId");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.OperatorDataModel", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableFieldDataModel", "TableFieldDataModelField")
                        .WithMany()
                        .HasForeignKey("TableFieldDataModelFieldId");
                });

            modelBuilder.Entity("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableFieldDataModel", b =>
                {
                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableFieldDataModel", "ReferenceField")
                        .WithMany()
                        .HasForeignKey("ReferenceFieldId")
                        .HasConstraintName("FK_referenced_FIELD");

                    b.HasOne("Involys.Repository.Api.Infrastructure.Data.Models.Alerts.TableDataModel", "Table")
                        .WithMany("TableFields")
                        .HasForeignKey("TableId");
                });
#pragma warning restore 612, 618
        }
    }
}
